### ISSUE TITLE
Fail to sync private repositories

### ISSUE THREAD

**Issue by mandre** [hubtty/hubtty#19]
Trying to subscribe to private repositories cause hubtty to throw errors:
```
2021-02-06 11:43:28,557 Exception checking repo <private>
Traceback (most recent call last):
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 995, in run
    gitrepo.get_repo(project.name, app.config)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/gitrepo.py", line 582, in get_repo
    return Repo(config.git_url + project_name, local_path)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/gitrepo.py", line 287, in __init__
    git.Repo.clone_from(self.url, self.path)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/git/repo/base.py", line 1032, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/git/repo/base.py", line 973, in _clone
    finalize_process(proc, stderr=stderr)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/git/util.py", line 329, in finalize_process
    proc.wait(**kwargs)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/<private> /home/martin/hubtty/<private>
  stderr: 'Cloning into '/home/martin/hubtty/<private>'...
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/<private>/'
```

And:
```
2021-02-06 11:43:33,156 Exception running task <SyncProjectTask [65, 500, 222]>
Traceback (most recent call last):
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1469, in _run
    task.run(self)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 369, in run
    changes = sync.query(query)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1629, in query
    response = self.get(q)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1519, in get
    self.checkResponse(r)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1504, in checkResponse
    raise Exception("Received %s status code: %s"
Exception: Received 422 status code: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://docs.github.com/v3/search/"}
```

**Comment by mandre** [comment]
Changing the `git-url` to `ssh://git@github.com` is enough to sync private repos.
