### ISSUE TITLE
Syntax error at "1197 state:open" in search string "_project_key:1197 state:open"

### ISSUE THREAD

**Issue by EmilienM** [hubtty/hubtty#30]
* In your Hubtty config file, add a project that doesn't exist in `additional-repositories`
* Run Hubbty, you should see an error when synchronizing
* Press enter in the project to list the PRs and it should immediately fail:

```
Traceback (most recent call last):
  File "/home/emilien/python-venv/bin/hubtty", line 10, in <module>
    sys.exit(main())
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/app.py", line 923, in main
    g.run()
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/app.py", line 360, in run
    self.loop.run()
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/view/project_list.py", line 540, in keypress
    key = super(ProjectListView, self).keypress(size, key)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/container.py", line 1626, in keypress
    key = self.focus.keypress(tsize, key)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/listbox.py", line 968, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/wimp.py", line 543, in keypress
    self._emit('click')
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/view/project_list.py", line 366, in onSelect
    self.app.changeScreen(view_change_list.ChangeListView(
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/view/change_list.py", line 382, in __init__
    self.refresh()
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/view/change_list.py", line 407, in refresh
    change_list = session.getChanges(self.query, self.unreviewed,
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/db.py", line 853, in getChanges
    q = self.session().query(Change).filter(self.search.parse(query))
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/search/__init__.py", line 53, in parse
    result = self.parser.parse(data, lexer=self.lexer)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/ply/yacc.py", line 192, in call_errorfunc
    r = errorfunc(token)
  File "/home/emilien/python-venv/lib64/python3.9/site-packages/hubtty/search/parser.py", line 448, in p_error
    raise hubtty.search.SearchSyntaxError('Syntax error at "%s" in search string "%s" (col %s)' % (
hubtty.search.SearchSyntaxError: Syntax error at "1197 state:open" in search string "_project_key:1197 state:open" (col 13)
```

**Comment by mandre** [comment]
Not sure if my PR is going to fix the root cause for your issue since you seem to have a DB that was busted due to a partial sync, however it should remove non-existing projects from your DB and might still help with the issue you're seeing.
