### ISSUE TITLE
Error while self-approving pull request

### ISSUE THREAD

**Issue by mandre** [hubtty/hubtty#33]
```
2021-06-08 09:23:57,235 Exception running task <UploadReviewTask 14736>
Traceback (most recent call last):
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1395, in _run
    task.run(self)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1250, in run
    sync.post('repos/%s/reviews' % (change_id,),
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1485, in post
    self.checkResponse(r)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.9/site-packages/hubtty/sync.py", line 1430, in checkResponse
    raise Exception("Received %s status code: %s"
Exception: Received 422 status code: {"message":"Unprocessable Entity","errors":["Can not approve your own pull request"],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-review-for-a-pull-request"}
```

**Comment by pabelanger** [comment]
You are not allowed to approve your own pull requests on github, this is a feature in github.

To me, it is a bug, but you cannot really do anything about it.
