### ISSUE TITLE
Initial setup could be more user friendly

### ISSUE THREAD

**Issue by stephenfin** [hubtty/hubtty#75]
(Mostly leaving this here as a note for future me - I'll try to fix this myself if you don't get to it before I do).

Having just installed `hubtty`, I try to run it and get the following:

```
$ hubtty
Traceback (most recent call last):
  File "/home/stephenfin/.local/bin/hubtty", line 8, in <module>
    sys.exit(main())
  File "/home/stephenfin/.local/lib/python3.10/site-packages/hubtty/app.py", line 897, in main
    g = App(args.server, args.palette, args.keymap, args.debug, args.verbose,
  File "/home/stephenfin/.local/lib/python3.10/site-packages/hubtty/app.py", line 254, in __init__
    self.config = config.Config(server, palette, keymap, path)
  File "/home/stephenfin/.local/lib/python3.10/site-packages/hubtty/config.py", line 144, in __init__
    self.path = self.verifyConfigFile(path)
  File "/home/stephenfin/.local/lib/python3.10/site-packages/hubtty/config.py", line 256, in verifyConfigFile
    self.copyDefault()
  File "/home/stephenfin/.local/lib/python3.10/site-packages/hubtty/config.py", line 287, in copyDefault
    copyfile(filename, CONFIG_PATH)
  File "/usr/lib64/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/hubtty/examples/reference-hubtty.yaml'
```

It would be nice to handle this better (i.e. without a stacktrace)

**Comment by stephenfin** [comment]
Actually, maybe this is packaging issue? I don't see these files being created in `$HOME/.local/share/hubtty` like I do for `gertty`...

**Comment by mandre** [comment]
I'm not getting the error when installing hubtty in a virtualenv, however I was able to replicate when installing with `pip install --user hubtty`.
