### ISSUE TITLE
IndexError: list index out of range error while syncing PR

### ISSUE THREAD

**Issue by mandre** [hubtty/hubtty#87]
I'm seeing the following trace in my logs.
```
2022-10-10 13:24:41,100 Exception running task <SyncPullRequestTask openshift/release/pulls/32431>
Traceback (most recent call last):
  File "/home/martin/.virtualenvs/hubtty/lib/python3.10/site-packages/hubtty/sync.py", line 1323, in _run
    task.run(self)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.10/site-packages/hubtty/sync.py", line 600, in run
    self._syncPullRequest(sync)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.10/site-packages/hubtty/sync.py", line 732, in _syncPullRequest
    remote_commit['parents'][0]['sha'])
IndexError: list index out of range
2022-10-10 14:25:15,936 Marking pull request openshift/release/pulls/32431 outdated
```

**Comment by mandre** [comment]
The commit in question has no parents:
```
$ gh api "repos/openshift/release/pulls/32431/commits" | jq '.[].parents'
[]
```
