### ISSUE TITLE
Sync in-line comments for commit no longer belonging to PR causes error

### ISSUE THREAD

**Issue by mandre** [hubtty/hubtty#90]
Seeing the following in my logs:
```
2022-11-25 09:56:18,445 Exception running task <SyncPullRequestTask openshift/release/pulls/34229>
Traceback (most recent call last):
  File "/home/martin/.virtualenvs/hubtty/lib/python3.11/site-packages/hubtty/sync.py", line 1328, in _run
    task.run(self)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.11/site-packages/hubtty/sync.py", line 600, in run
    self._syncPullRequest(sync)
  File "/home/martin/.virtualenvs/hubtty/lib/python3.11/site-packages/hubtty/sync.py", line 846, in _syncPullRequest
    comment = message.createComment(file_id, remote_comment['id'], account,
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'createComment'
```

**Comment by mandre** [comment]
Also what is special in that PR is that the commit was the original commit of the PR, then a bunch of modification, then forced pushed back to the original commit.
